### ISSUE TITLE
Add possibility to calculate insuline units

### ISSUE THREAD

**Issue by NotSoImportant** [Faltenreich/Diaguard#13]
Why can I enter a bolus factor when I cannot use it later?
Of course this can only be a hint, not a medical advice, but I would love to get it.

**Comment by Faltenreich** [comment]
Good question! Bolus factors were once used for the bolus calculator which has been removed due to legal reasons. Now they only serve a documentary purpose.

**Comment by NotSoImportant** [comment]
Thanks. Kind of can understand it. However still it would have been a valuable feature.
