### ISSUE TITLE
Make dots in blood sugar curve optional

### ISSUE THREAD

**Issue by drunken-dwarf** [Faltenreich/Diaguard#21]
I own and use a CGM system and thus sometimes add a lot of entries in a short time span. This has the effect that I can no longer acurately see the curve because the dots overlap and hide the actual line.
Making the dots hideable would fix this issue.

**Comment by Faltenreich** [comment]
Good idea! This should only take little effort, since the timeline is already configurable via the three-dot menu item in the Toolbar. Another preference could be added which changes the style of the "dots".
