### ISSUE TITLE
Insulin calculator

### ISSUE THREAD

**Issue by drunken-dwarf** [Faltenreich/Diaguard#23]
The app has all the data it needs to calculate the insulin needed for a given meal.
Currently I use Tasker to extract all values from the settings and UI to calculate my insulin.

A native calculator would greatly increase the usability and reduce errors.

**Comment by Faltenreich** [comment]
Technically you are right but sadly this feature has been removed due to legal reasons. 

Read here for more information: https://diaguard.wordpress.com/2018/05/01/diaguard-2-4-3/
