### ISSUE TITLE
Allow precise bolus-factors

### ISSUE THREAD

**Issue by drunken-dwarf** [Faltenreich/Diaguard#26]
I'd like to be able to change my bolus factors in 0.25 steps. 2.75 gets rounded up to 2.8 though.
Allowing one more decimal place would not hurt the usability.

**Comment by Faltenreich** [comment]
Thank you for your suggestion! In fact right before your feedback I have received another user requests via mail regarding this topic and decided to support more digits while making it user-customizable. You can follow the implementation on https://github.com/Faltenreich/Diaguard/tree/feature/decimals.
