### ISSUE TITLE
Food database entries from external sources use "kJ" as "kcal"

### ISSUE THREAD

**Issue by drunken-dwarf** [Faltenreich/Diaguard#35]
I noticed that pre-filled entries from outside sources have wrong kJ/kcal values. When compared to the entry on openfoodfacts, it is clear that the app reads the kJ value as kcal, which is then converted back to a very high kJ value.

Example in the app:
"Apfel birnen saft naturtrüb direktsaft 100%" lists 736,4 kJ (176 kcal)

Entry on openfoodfacts lists 176 kj (42 kcal)
https://de.openfoodfacts.org/produkt/4388860589672/apfel-birnen-saft-naturtr%C3%BCb-direktsaft-100-rewe

**Comment by Faltenreich** [comment]
Fixed by #47 but unfortunately existing or already-requested data will not be affected by the bugfix, since there is currently no way differentiating updates from OpenFoodFacts or by the user, so I decided agsinst force updating existing data in order to not override any user input.
