### ISSUE TITLE
Confirm button disapears in long meal lists

### ISSUE THREAD

**Issue by coastgnu** [Faltenreich/Diaguard#40]
Diaguard 3.11.
Android 13 auf Galaxy A71

Der Bestätigungs Knopf rutscht bei längeren Mahlzeit Listen tief unter den Bildschirmrand und ist nicht mehr erreichbar. 

Die Eingabe kann nicht bestätigt werden und wird nicht übernommen.

Mehr als zwei Einträge pro Mahlzeit sind nicht mehr möglich!

**Comment by Faltenreich** [comment]
Korrigiert mit https://github.com/Faltenreich/Diaguard/releases/tag/version%2F3.12.0
