### ISSUE TITLE
support data from CGM devices like Medtronic 640

### ISSUE THREAD

**Issue by nuraiman** [Faltenreich/Diaguard#8]
It would be nice to add support to load data from CGM devices like Medtronic 640.
It needs to read data from:
 https://github.com/pazaan/600SeriesAndroidUploader or xDrip app.

**Comment by Faltenreich** [comment]
This feature would be great without question but I fear that legal reasons prevent it from being realized. 

> Please note - this project has no association with and is not endorsed by: 
> 
> Medtronic
> 
> Ascensia Diabetes Care (formerly Bayer Diabetes Care)

[600SeriesAndroidUploader ](https://github.com/pazaan/600SeriesAndroidUploader/wiki)

> The app is not provided in Google Play - you have to build it from source code by yourself for legal reasons.

[xDrip/AndroidAPS](https://androidaps.readthedocs.io/en/latest/EN/index.html)

I am unable to integrate a connection between Diaguard and CGM devices without breaking terms and conditions. The only legal way seems to be contacting the manufacturers of these devices and integrating the connection in collaboration with them. Sadly this is something way out of my league as it involves complex and costly processes regarding medical apps which I [do not want to touch again](https://diaguard.wordpress.com/2018/05/01/diaguard-2-4-3/).

I hope you understand this and therefore respect my decision of closing this issue.
